### PR TITLE
:children_crossing: (src): lift mouseUp events to app level

### LINKED ISSUE #6: Listen for mouseUps/mouseDowns across the entire page instead of just inside the canvas.
This is open to discussion, but there's some dodgy behavior when dragging the mouse outside the bounds of the canvas and then releasing. Currently, the canvas still thinks we're drawing when we reenter the canvas.

### PR DESCRIPTION
**Pull request by fakemonster**
To fix #6. Listens for mouseUp across the app, but still only listens for mouseDown within the Oscilloscope.

### CODE REVIEW

**Comment by clarkenciel** [comment]
`:children-crossing:` -> `:children_crossing:`

**Review by clarkenciel — COMMENTED** [review]
the idea here is that we'll now track motions across the whole page?

**Comment by fakemonster** [comment]
That was the idea, though in testing (since it's on the app level),
onGestureEnd still doesn't fire if you release the mouse _underneath_ the
WoolyWilly since that's where the App div ends

**Comment by clarkenciel** [comment]
@fakemonster is it possible to have that div span the entire page?

**Comment by fakemonster** [comment]
Root and app elements are now 100% height so it tracks across the screen. If you try to mouseUp outside of that you got an attitude problem

**Review by clarkenciel — APPROVED** [review]

**Pull request merged**
